# -*- coding: utf-8 -*-
"""les2_task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-uqXQbXgmYWm21rvh7V7889DUhvUgrV
"""

#Сформировать из введенного числа обратное по порядку входящих в него цифр и вывести на экран. Например, если введено число 3486, надо вывести 6843

n = input('Введите число: ')
print(n[::-1])