# -*- coding: utf-8 -*-
"""les2_task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-uqXQbXgmYWm21rvh7V7889DUhvUgrV
"""

#Посчитать четные и нечетные цифры введенного натурального числа. Например, если введено число 34560, в нем 3 четные цифры (4, 6 и 0) и 2 нечетные (3 и 5)
n = abs(int(input("Введите натуральное число: ")))
even_n = 0
odd_n = 0

if n == 0:
    even_n = 1
while n > 0:
  if n % 2 == 0:
    even_n += 1
  else:
    odd_n += 1
  n = n // 10
print(f'Количество четных чисел: {even_n}, а нечетных: {odd_n}')